### PR TITLE
Update image to use Ruby 3.1.6

### PR DESCRIPTION
**Pull request by erikbrannstrom**
## Changes
- Move the Ruby version to a single place (`.ruby-version`) for easier updates (and potential automation in the future)
- Update Ruby to 3.1.6

### CODE REVIEW

**Review by annlund — APPROVED** [review]
Good idea! Haven't really tested it for myself, but the changes work in CircleCI and that's the important thing I guess 👍

**Review by louiced — APPROVED** [review]
I guess it looks good, but I'm not sure how to test it.

**Review by viktorsommar — APPROVED** [review]
LGTM! But I haven't tested it either, would be interesting to know the best way to do that @erikbrannstrom 🕵🏻

**Comment by erikbrannstrom** [comment]
The only way to see if it works properly (i.e. creates the expected image) is to login to our account on DockerHub and ensure the image exists there (which it does!).

The biggest reason I wanted some extra eyes here was to show that `.ruby-version` is now the single source of truth for which Ruby version will be used when creating the image.

**Pull request merged**
